// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZbx3w1XO8bdg1V8o9q6lmEwyOlND2a0',
    appId: '1:1071537908093:web:788498cee4fca8a18e8414',
    messagingSenderId: '1071537908093',
    projectId: 'ecomerce-2e9fc',
    authDomain: 'ecomerce-2e9fc.firebaseapp.com',
    storageBucket: 'ecomerce-2e9fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFgDd62XItEdohlOcqFhtT7XvVqCiwejw',
    appId: '1:1071537908093:android:06cacd8d8db4fa128e8414',
    messagingSenderId: '1071537908093',
    projectId: 'ecomerce-2e9fc',
    storageBucket: 'ecomerce-2e9fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsk8zVmPDU5ompEYbiGmZs72mkGPEZKEk',
    appId: '1:1071537908093:ios:ee06c2601fc82b968e8414',
    messagingSenderId: '1071537908093',
    projectId: 'ecomerce-2e9fc',
    storageBucket: 'ecomerce-2e9fc.firebasestorage.app',
    iosBundleId: 'com.example.session3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkZbx3w1XO8bdg1V8o9q6lmEwyOlND2a0',
    appId: '1:1071537908093:web:6b4443985014fab68e8414',
    messagingSenderId: '1071537908093',
    projectId: 'ecomerce-2e9fc',
    authDomain: 'ecomerce-2e9fc.firebaseapp.com',
    storageBucket: 'ecomerce-2e9fc.firebasestorage.app',
  );
}
