// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi7bExWwtAiVykB9CVakQ6cPRinCWModw',
    appId: '1:560321518411:web:2f131b60b788330acd66ce',
    messagingSenderId: '560321518411',
    projectId: 'ecommerce-enyoi',
    authDomain: 'ecommerce-enyoi.firebaseapp.com',
    storageBucket: 'ecommerce-enyoi.firebasestorage.app',
    measurementId: 'G-C4RHNF71BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKisDx2aMokQuWLLg3PYcC_B6E0Y1tbEQ',
    appId: '1:560321518411:android:2c5ec1b3f20d452ecd66ce',
    messagingSenderId: '560321518411',
    projectId: 'ecommerce-enyoi',
    storageBucket: 'ecommerce-enyoi.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnTa8IqJWFl5-oy4uKixyAhJ_Hej_zNyY',
    appId: '1:560321518411:ios:ac6245121f0072fccd66ce',
    messagingSenderId: '560321518411',
    projectId: 'ecommerce-enyoi',
    storageBucket: 'ecommerce-enyoi.firebasestorage.app',
    iosBundleId: 'com.example.session3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi7bExWwtAiVykB9CVakQ6cPRinCWModw',
    appId: '1:560321518411:web:75fefdfcbee7132dcd66ce',
    messagingSenderId: '560321518411',
    projectId: 'ecommerce-enyoi',
    authDomain: 'ecommerce-enyoi.firebaseapp.com',
    storageBucket: 'ecommerce-enyoi.firebasestorage.app',
    measurementId: 'G-KV7MVWG2K2',
  );
}
